name: Generate verifiers

on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ./.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn generate-workflows
      - run: cp *.nix out/
      - run: cp flake.lock out/
      - run: cp flake.lock out/
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DIST_DEPLOY_KEY }}
          external_repository: DeployDAO/verified-programs-builder
          publish_branch: master
          publish_dir: ./out/
